export { listVisitsReadyToBill } from './ready';
export { createBill } from './create';
export type { CreateBillInput, ServiceChargeInput } from './create';
export { recordPayment } from './payment';
export type { RecordPaymentInput } from './payment';
export { collectConsultationFee, CONSULTATION_FEE_DESCRIPTION } from './consultation-fee';
export type { CollectConsultationFeeInput } from './consultation-fee';
export { collectFrontDeskCharges } from './front-desk-charges';
export type { CollectFrontDeskChargesInput, FrontDeskChargeInput } from './front-desk-charges';
export { addCounterSaleItem, finalizeCounterSale } from './counter-sale';
export type { AddCounterSaleItemInput, FinalizeCounterSaleInput } from './counter-sale';
export { searchBills } from './search';
export { getBillDetail } from './detail';
export { generateBillNumber } from './bill-number';
export { DEFAULT_TAX_PERCENT } from './constants';
